namespace Syntra.SourceGenerator.Tests;

public sealed class SyntraHandlerGeneratorTests
{
    private const string HintName = "SyntraHandlerRegistrationHints.g.cs";

    // HandlerRegistrationEmitter builds this with explicit \n line endings so generated
    // output is deterministic regardless of host OS - matched explicitly here rather than
    // relying on Environment.NewLine, which would make this test fail on Linux CI.
    private static string HandlerCountSource(int count) =>
        string.Join(
            "\n",
            "// <auto-generated />",
            "namespace Syntra.Generated;",
            "internal static class SyntraHandlerRegistrationHints",
            "{",
            $"    public const int HandlerCount = {count};",
            "}",
            "");

    [Fact]
    public async Task Single_handler_generates_HandlerCount_one_and_reports_nothing()
    {
        const string source = """
            using System.Threading;
            using System.Threading.Tasks;
            using Syntra.Abstractions.Requests;
            using Syntra.Abstractions.Handlers;
            using Syntra.Abstractions.Results;

            public sealed record PingCommand : ICommand;

            public sealed class PingCommandHandler : ICommandHandler<PingCommand>
            {
                public Task<Result> HandleAsync(PingCommand request, CancellationToken cancellationToken = default) =>
                    Task.FromResult(Result.Success());
            }
            """;

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(1)));
    }

    [Fact]
    public async Task No_handlers_generates_HandlerCount_zero()
    {
        const string source = """
            public class NotAHandler;
            """;

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(0)));
    }

    [Fact]
    public async Task Two_handlers_for_the_same_request_reports_SYN102_on_each()
    {
        const string source = """
            using System.Threading;
            using System.Threading.Tasks;
            using Syntra.Abstractions.Requests;
            using Syntra.Abstractions.Handlers;
            using Syntra.Abstractions.Results;

            public sealed record PingCommand : ICommand;

            public sealed class PingCommandHandlerOne : ICommandHandler<PingCommand>
            {
                public Task<Result> HandleAsync(PingCommand request, CancellationToken cancellationToken = default) =>
                    Task.FromResult(Result.Success());
            }

            public sealed class PingCommandHandlerTwo : ICommandHandler<PingCommand>
            {
                public Task<Result> HandleAsync(PingCommand request, CancellationToken cancellationToken = default) =>
                    Task.FromResult(Result.Success());
            }
            """;

        var expectedOne = GeneratorVerifier
            .Diagnostic(DiagnosticDescriptors.MultipleHandlersForRequest)
            .WithSpan(9, 1, 13, 2)
            .WithArguments("PingCommand");
        var expectedTwo = GeneratorVerifier
            .Diagnostic(DiagnosticDescriptors.MultipleHandlersForRequest)
            .WithSpan(15, 1, 19, 2)
            .WithArguments("PingCommand");

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(2)), expectedOne, expectedTwo);
    }

    [Fact]
    public async Task Handler_missing_CancellationToken_reports_SYN103()
    {
        const string source = """
            using System.Threading;
            using System.Threading.Tasks;
            using Syntra.Abstractions.Requests;
            using Syntra.Abstractions.Handlers;
            using Syntra.Abstractions.Results;

            public sealed record PingCommand : ICommand;

            public sealed class PingCommandHandler : ICommandHandler<PingCommand>
            {
                public Task<Result> HandleAsync(PingCommand request) =>
                    HandleAsync(request, CancellationToken.None);

                public Task<Result> HandleAsync(PingCommand request, CancellationToken cancellationToken) =>
                    Task.FromResult(Result.Success());
            }
            """;

        var expected = GeneratorVerifier
            .Diagnostic(DiagnosticDescriptors.HandlerMissingCancellationToken)
            .WithSpan(9, 1, 16, 2)
            .WithArguments("global::PingCommandHandler");

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(1)), expected);
    }

    [Fact]
    public async Task Request_without_a_handler_reports_SYN101()
    {
        const string source = """
            using Syntra.Abstractions.Requests;
            using Syntra.Abstractions.Results;

            public sealed record LonelyCommand : ICommand;
            """;

        var expected = GeneratorVerifier
            .Diagnostic(DiagnosticDescriptors.RequestHasNoHandler)
            .WithSpan(4, 22, 4, 35)
            .WithArguments("LonelyCommand");

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(0)), expected);
    }

    // ICommandHandler<TCommand> constrains TCommand : ICommand at the interface level, so a type that
    // genuinely implements the real Syntra.Abstractions.Handlers.ICommandHandler<> can never violate
    // this check - the compiler already enforces it. But the generator's IsCommandHandler test matches
    // purely on metadata name ("ICommandHandler`1"/"ICommandHandler`2"), not on the actual interface's
    // identity/namespace, so an unrelated same-named interface is enough to trigger SYN104 for a request
    // type that never implements the real ICommand. Documents that blind spot rather than an impossible
    // "normal" trigger.
    [Fact]
    public async Task Command_handler_whose_command_does_not_implement_ICommand_reports_SYN104()
    {
        const string source = """
            using System.Threading;
            using System.Threading.Tasks;
            using Syntra.Abstractions.Requests;
            using Syntra.Abstractions.Handlers;
            using Syntra.Abstractions.Results;

            namespace Decoy
            {
                public interface ICommandHandler<TCommand> { }
            }

            public sealed record PlainRequest : IRequest<Result>;

            public sealed class PlainRequestHandler : IRequestHandler<PlainRequest, Result>, Decoy.ICommandHandler<PlainRequest>
            {
                public Task<Result> HandleAsync(PlainRequest request, CancellationToken cancellationToken = default) =>
                    Task.FromResult(Result.Success());
            }
            """;

        var expected = GeneratorVerifier
            .Diagnostic(DiagnosticDescriptors.CommandDoesNotImplementICommand)
            .WithSpan(14, 1, 18, 2)
            .WithArguments("PlainRequest");

        await GeneratorVerifier.VerifyAsync(source, (HintName, HandlerCountSource(1)), expected);
    }
}
