using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Syntra.SourceGenerator;

/// <summary>
/// Emits generated registration hints (see <see cref="SyntraHandlerGenerator"/>).
/// </summary>
internal static class HandlerRegistrationEmitter
{
    public static void EmitHandlerCount(SourceProductionContext context, int count)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated />\n");
        sb.Append("namespace Syntra.Generated;\n");
        sb.Append("internal static class SyntraHandlerRegistrationHints\n");
        sb.Append("{\n");
        sb.Append("    public const int HandlerCount = ").Append(count).Append(";\n");
        sb.Append("}\n");
        context.AddSource("SyntraHandlerRegistrationHints.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
