using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Syntra.SourceGenerator;

/// <summary>
/// Emits generated registration hints (see <see cref="SyntraHandlerGenerator"/>).
/// </summary>
internal static class HandlerRegistrationEmitter
{
    public static void EmitHandlerCount(SourceProductionContext context, int count)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace Syntra.Generated;");
        sb.AppendLine("internal static class SyntraHandlerRegistrationHints");
        sb.AppendLine("{");
        sb.Append("    public const int HandlerCount = ").Append(count).AppendLine(";");
        sb.AppendLine("}");
        context.AddSource("SyntraHandlerRegistrationHints.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
