<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Syntra.WorkerService-82fd980f-ab1c-4dda-9ef5-90dd620ca8ef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Syntra.DependencyInjection\Syntra.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
